steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$_GCP_PROJECT_ID/$_SERVICE_NAME:$_IMAGE_V', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$_GCP_PROJECT_ID/$_SERVICE_NAME:$_IMAGE_V']
  - name: gcr.io/cloud-builders/gcloud
    args: [
      'run',
      'deploy',
      '$_SERVICE_NAME-$_IMAGE_V',
      '--image',
      'gcr.io/$_GCP_PROJECT_ID/$_SERVICE_NAME:$_IMAGE_V',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--port=$_PORT',
      '--set-env-vars=MONGODB_CONNECTION_STRING=$_MONGODB_CONNECTION_STRING,MONGODB_DATABASE=$_MONGODB_DATABASE,AUTH0_ISSUER_BASE_URL=$_AUTH0_ISSUER_BASE_URL,AUTH0_AUDIENCE=$_AUTH0_AUDIENCE',
      '--allow-unauthenticated',
    ]
